#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Shanghai"

		delete system.ntp.server
		add_list system.ntp.server="ntp.aliyun.com"
		add_list system.ntp.server="cn.ntp.org.cn"

		set system.@imm_init[0].system_chn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://mirrors.vsean.net/openwrt"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi

sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"

# fix distfeeds
sed -i 's/^option check_signature/#option check_signature/' /etc/opkg.conf

cp /etc/opkg/distfeeds.conf /etc/opkg/distfeeds.conf.99.bak
cat << "EOF" > /etc/opkg/distfeeds.conf
src/gz immortalwrt_base https://downloads.immortalwrt.org/releases/packages-24.10/aarch64_cortex-a53/base
src/gz immortalwrt_luci https://downloads.immortalwrt.org/releases/packages-24.10/aarch64_cortex-a53/luci
src/gz immortalwrt_packages https://downloads.immortalwrt.org/releases/packages-24.10/aarch64_cortex-a53/packages
src/gz immortalwrt_routing https://downloads.immortalwrt.org/releases/packages-24.10/aarch64_cortex-a53/routing
src/gz immortalwrt_telephony https://downloads.immortalwrt.org/releases/packages-24.10/aarch64_cortex-a53/telephony
EOF

exit 0