#CI项目
name: QCA-ALL

#CI计划
on:
  #自动清理：每天早上5点
#  schedule:
 #  - cron: 0 21 * * *
  #自动编译：当Auto-Clean运行完成后
  #workflow_run:
  #  workflows: ["Auto-Clean"]
  #  types:
  #   - completed
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，仅限一个'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件'
        default: false
        required: false
        type: boolean
      COMMIT:
        description: '指定Commit'
        required: false
        type: string


#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 2
      matrix:
        TARGET: [IPQ60XX-WIFI-NO]
        REPO_INFO:
          - {SOURCE: VIKINGYFY/immortalwrt, BRANCH: main, NAME: OWRT, SUFFIX: IMM}
          - {SOURCE: VIKINGYFY/immortalwrt, BRANCH: main, NAME: OWRT, SUFFIX: IMM, USEAPK: 'false'}

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: ${{matrix.REPO_INFO.NAME}}
      #默认地址
      WRT_IP: 192.168.3.18
      #默认密码，仅作提示，修改无用
      WRT_PW: none
      #源码链接
      WRT_REPO: https://github.com/${{matrix.REPO_INFO.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.REPO_INFO.BRANCH || 'main'}}
      #源码名称
      WRT_SOURCE: ${{matrix.REPO_INFO.SOURCE}}
      #源码COMMIT
      WRT_COMMIT: ${{inputs.COMMIT}}
      #后缀名称
      WRT_SUFFIX: ${{matrix.REPO_INFO.SUFFIX}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
      #APK or IPK
      WRT_USEAPK: ${{matrix.REPO_INFO.USEAPK || 'true'}}

